config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users

  devise_scope :users do
    resources :notes, concerns: :paginatable
    get "notes/tag/:tag(/page/:page)" => "notes#tagged", as: :notes_tagged
    post "search" => "notes#search", as: :note_search
    get "tags/cloud" => "notes#tag_cloud", as: :tag_cloud
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  paginates_per 12
  acts_as_taggable_on :tags
  dragonfly_accessor :image
  
  belongs_to :user

  validates :title, :markdown, :html, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,:recoverable, 
  devise :database_authenticatable, :rememberable, :validatable

  validates :name, presence: true

  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :mobile?

  def mobile?
    browser.device.mobile?
  end
  helper_method :mobile?
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes
  def index
    @notes = current_user.notes.order(created_at: :desc).page(params[:page])
  end

  # GET /notes/1
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to notes_path, notice: "Note was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      redirect_to notes_path, notice: "Note was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    redirect_to notes_path, notice: "Note was successfully destroyed."
  end

  def tagged
    @tag_name = params[:tag].downcase
    @notes = current_user.notes.tagged_with(@tag_name).order(created_at: :desc).page(params[:page])
  end

  def search
    @query = params.require(:note).permit(:query)[:query]
    redirect_to root_path and return unless @query.present?

    service = SearchService.call(
      user: current_user,
      query: @query,
      page: params[:page]
    )
    @notes = service.notes
  end

  def tag_cloud
    @tags = current_user.notes.tag_counts_on(:tags)
  end

  private
    
  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = current_user.notes.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:title, :markdown, :html, :tag_list, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icons_helper.rb
module IconsHelper
  def fa_solid(icon, size: 2, options: {})
    tag.span(class: "#{options.dig(:class)} icon") do
      tag.i(class: "fas fa-#{icon} fa-size-#{size}")
    end
  end

  def fa_regular(icon, size: 2)
    tag.span(class: "icon") do
      tag.i(class: "far fa-#{icon} fa-size-#{size}")
    end
  end

  def fa_brands(icon, size: 1)
    tag.span(class: "icon") do
      tag.i(class: "fab fa-#{icon} fa-size-#{size}")
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/_flash_messages.html.haml
- if flash[:alert]
  %article.message.is-danger
    .message-body
      = flash[:alert]

- if flash[:notice]
  %article.message.is-success
    .message-body
      = flash[:notice]

app/views/layouts/_navbar.html.haml
%nav.navbar(role="navigation" aria-label="main navigation" data-controller="navbar")
  .navbar-brand
    = link_to root_path, class: "navbar-item has-text-primary" do
      = fa_regular "sticky-note"
      .subtitle.pl-4.has-text-primary Notes
    = link_to "#", class: "navbar-burger", role: "button", "aria-label" => "menu", "aria-expanded" => "false", "data-target" => "navbar-mobile", data: { "navbar-target" => "burger", action: "click->navbar#burgerClicked" } do
      %span(aria-hidden="true")
      %span(aria-hidden="true")
      %span(aria-hidden="true")

  #navbar-mobile.navbar-menu(data-navbar-target="menu")
    .navbar-start
      = form_with scope: current_user.notes.new, url: note_search_path, method: :post, class: "navbar-item" do |form|
        .is-flex.is-flex-direction-row
          = form.text_field :query, placeholder: "Search ...", class: "input query"
          .pl-4
          %button(type="submit" class="button is-primary")
            = fa_solid "search", size: 1

    .navbar-end
      .navbar-item
        .buttons
          .is-flex.is-flex-direction-row.is-align-items-center
            = link_to new_note_path, class: "button is-primary" do
              = fa_solid "plus", size: 1
            - if mobile?
              %span Start new note
      .navbar-item
        .buttons
          .is-flex.is-flex-direction-row.is-align-items-center
            = link_to tag_cloud_path, class: "button is-primary" do
              = fa_solid "tags", size: 1
            - if mobile?
              %span Tag Cloud
      .navbar-item
        .buttons
          .is-flex.is-flex-direction-row.is-align-items-center
            = button_to destroy_user_session_path, method: :delete, title: "Log out", class: "button is-primary log-out" do
              = fa_solid "lock", size: 1
            - if mobile?
              %span Log out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Notes
      = yield :title 
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    = favicon_link_tag asset_path("favicon.png")
    %link(rel="apple-touch-icon" href="#{asset_path("apple-touch.png")}")
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", defer: true

  %body(id="#{'authenticated' if user_signed_in?}" class="#{controller_name}_#{action_name}")
    - if user_signed_in?
      = render "/layouts/navbar"
      %div(class="#{'mobile-padding' if mobile?}")
        = yield
    - else
      .is-page-vertical-centered
        .is-page-horizontal-centered
          .title.is-1 Notes
        .pt-4.mt-4
          = yield

    = render partial: "/layouts/flash_messages"
    
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js", defer: true

app/views/notes/_form.html.haml
= form_with(model: note) do |form|
  -#<% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>

  .columns
    - if note.image&.url
      .column.is-one-quarter
        %figure.image.is-128x128
          = image_tag note.image.url
    .column.is-two-thirds
      .file(class="#{'has-name is-fullwidth' if note.image}")
        %label.file-label
          = form.file_field :image, class: "file-input"
          %span.file-cta
            %span.file-icon
              %i.fas.fa-upload
            %span.file-label
              Choose a file ...
          - if note.image
            %span.file-name
              = note.image_uid
      -#.field
        .control
          = form.file_field :image

  .columns
    .column.is-half
      .field
        = form.label :title, class: "label"
        .control
          = form.text_field :title, class: "input #{'is-danger' if note.errors[:title].any?}", value: note.title
          - if note.errors[:title].any?
            .has-text-danger.is-size-7
              = note.errors[:title].join(', ')
    .column.is-half
      .field
        = form.label :tag_list, class: "label"
        .control
          = form.text_field :tag_list, class: "input #{'is-danger' if note.errors[:tag_list].any?}", value: note.tag_list.join(', ')
          .is-size-7.has-text-weight-lighter comma separated like "cooking, indian, spicy"
          - if note.errors[:tag_list].any?
            .has-text-danger.is-size-7
              = note.errors[:tag_list].join(', ')

  .columns(data-controller="markdown")
    .column.is-half
      .field
        = form.label :markdown, class: "label"
        .control
          = form.text_area :markdown, class: "textarea #{'is-danger' if note.errors[:markdown].any?}", value: note.markdown, data: { "markdown-target" => "markdown", action: "keyup->markdown#markdownChanged" }
          - if note.errors[:markdown].any?
            .has-text-danger.is-size-7
              = note.errors[:markdown].join(', ')
    .column.is-half
      = form.hidden_field :html, value: note.html, data: { "markdown-target" => "html" }
      .is-size-5
        Preview
      .preview(data-markdown-target="preview")
        = raw note.html
  
  .columns
    .column
      .field
        .control
          = form.submit "#{note.persisted? ? 'Update note' : 'Create note'}", class: "button is-primary"

app/views/notes/_note.html.haml
.card.note
  - if note.image
    .card-image
      %figure(class="image")
        = image_tag note.image.url
  .card-content
    .media
      .media-content
        %p.title.is-3
          = link_to note.title, note_path(note)
        %time.is-size-8.has-text-weight-lighter(datetime="#{note.created_at.to_formatted_s(:note_created_at)}")
          = note.created_at.to_formatted_s(:note_created_at)
    .content
      .is-flex.is-flex-direction-column.html
        = raw note.html
      .is-flex.is-flex-direction-row.pt-4
        - note.tags.each.with_index do |tag, index|
          %span.tag.tag--small.is-light(class="#{'ml-2' if index > 0}")
            = link_to tag.name.downcase, notes_tagged_path(tag.name.downcase)
  %footer.card-footer
    = link_to edit_note_path(note), class: "card-footer-item" do
      = fa_solid "save", size: 1
      Edit
    .card-footer-item
      = button_to note_path(note), method: :delete, class: "button is-white has-text-danger" do
        = fa_solid "trash", size: 1, options: {class: "mr-0"}
        %span
          Delete
          

app/views/notes/edit.html.haml
- content_for :title do
  \- Edit existing note

.container
  .subtitle.pt-3
    Edit existing note

  .pt-4
    = render 'form', note: @note

app/views/notes/index.html.haml
- content_for :title do
  \- All notes

.container
  .pt-4
    - @notes.in_groups_of(mobile? ? 1 : 4).each do |group|
      .columns
        - group.compact.each do |note|
          .column.is-one-quarter
            = render partial: "note", locals: { note: note }

  .pt-4.mt-4.mb-4.pb-4.is-page-horizontal-centered
    = paginate @notes, views_prefix: "pagination"

app/views/notes/new.html.haml
- content_for :title do
  \- Start new note

.container
  .subtitle.pt-3
    Start new note

  .pt-4
    = render 'form', note: @note

app/views/notes/search.html.haml
- content_for :title do
  \- Notes for '#{@query}'

.container
  .is-flex.is-align-items-center
    .title.pt-3
      Notes for
      %span.tag.is-size-5
        = @query
    = link_to root_path, class: "button is-primary ml-4 is-size-8 mb-2" do
      = fa_solid "times", size: 1

  .pt-4
    - @notes.in_groups_of(3).each do |group|
      .columns
        - group.compact.each do |note|
          .column.is-one-third
            = render partial: "note", locals: { note: note }

  

app/views/notes/show.html.haml
- content_for :title do
  \-
  = @note.title

.container
  - if @note.image
    %figure(class="image #{mobile? ? 'is-max-width' : 'is-256x256'} is-rounded")
      = image_tag @note.image.url

  .title.pt-3.mb-0
    = @note.title
  
  %time.is-size-8.has-text-weight-lighter(datetime="#{@note.created_at.to_formatted_s(:note_created_at)}")
    = @note.created_at.to_formatted_s(:note_created_at)

  .html
    = raw @note.html
  
  .is-flex.is-flex-direction-row.pt-4
    - @note.tags.each.with_index do |tag, index|
      %span.tag.tag--small.is-light(class="#{'ml-2' if index > 0}")
        = link_to tag.name.downcase, notes_tagged_path(tag.name.downcase)

app/views/notes/tag_cloud.html.haml
- content_for :title do
  \- Tag cloud

.container
  .pt-4.tag_cloud
    - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
      = link_to notes_tagged_path(tag.name) do
        %span.tag(class=css_class)
          = tag.name

app/views/notes/tagged.html.haml
- content_for :title do
  \- Notes tagged with '#{@tag_name}'

.container
  .title.pt-3
    Notes tagged with 
    %span.tag.is-size-5
      = @tag_name

  .pt-4
    - @notes.in_groups_of(3).each do |group|
      .columns
        - group.compact.each do |note|
          .column.is-one-third
            = render partial: "note", locals: { note: note }

  .pt-4.mt-4.mb-4.pb-4.is-page-horizontal-centered
    = paginate @notes